### ISSUE TITLE
Se debe ocultar la alerta una vez que todos los campos están ya completos

### ISSUE THREAD

**Issue by kholostyak17** [YifanYes/Form-Validations#1]
- Como se adjunta en la siguiente imagen, la alerta no se oculta cuando los campos ya se encuentran completados: https://github.com/YifanYes/Form-Validations/blob/a9d8603f254f8c56bb2dd10c41e4a0973f8cd027/src/app.js#L69
![image](https://user-images.githubusercontent.com/80543950/127172916-40c19e3b-7ad9-427e-9d48-43eb32387090.png)
https://github.com/YifanYes/Form-Validations/blob/a9d8603f254f8c56bb2dd10c41e4a0973f8cd027/src/app.js#L90
Habría que realizar una comprobación en el caso de que todos los campos ya no se encuentren vacíos y ocultar la alerta, o mostrar un feedback de que todo esta correcto.

- A la casilla de opciones para elegir país le falta incluirle una opción por defecto, y ponerle un `<label>` para que quede alineada  con el resto de elementos:
https://github.com/YifanYes/Form-Validations/blob/a9d8603f254f8c56bb2dd10c41e4a0973f8cd027/src/index.html#L110

- _(Recomendación) Con el atributo `title` dentro de un input podemos especificar cual es el formato requerido, por si el usuario no lo sabe._
![image](https://user-images.githubusercontent.com/80543950/127176465-7721cbb4-7e12-4350-9ad9-557d52cbf494.png)
![image](https://user-images.githubusercontent.com/80543950/127176664-79ed5b1a-26fc-43f6-b9a3-6844e48c7526.png)

**Comment by YifanYes** [comment]
Vale, ya he añadido el label y los atributos title, pero he estado haciendo pruebas y no me salta lo de la alerta, porque ahora si tienes algún campo sin completar simplemente en el mismo campo te dice que faltan cosas o que no es válido

**Comment by kholostyak17** [comment]
muy bien, lo de las alertas individuales solo era un ejercicio extra, así que solucionado!!
